# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6abcbfbde699dccd18bcb4ba6fd8c9c33b0f9bd4921440bbd9c0605679e2c3d0824bdc9f7d9237aadc312a6ab5889f63e7b4523ffe9373a251bae85f2aab0816

test:
  secret_key_base: 54a7426f4ce1c7d97fa9419e24d5679cc7433396d24b3de815a73ea5708773316c97382d4d337d5a84eba0f0d1bfcdee6bbbd1d039f35ca3d7534f63f6f985db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
